- README.md
- scripts/deployment/README.md
> doc: readme

- scripts/deployment/globals_gnosis_mainnet.json
- Updating agent factory address;
- Updating agent mech address.
> chore: updating agent factory address

- contracts/AgentMech.sol
- test/AgentMech.js
- Adding more request Id tracking and getters;
- Add virtual functions to facilitate actions with requests;
- No current mech ABI has been changed.
> feat: adding more request Id tracking and getters

- contracts/AgentMech.sol
- test/AgentMech.js
Sorry for this rather messy fix. It means the trader does not need to change anything.
> chore: messy fix to static request id requirement

- contracts/integrations/nevermined/AgentMechSubscription.sol
- Adjusting to dynamic subscription price.
> refactor: dynamic subscription price

- contracts/AgentFactory.sol
- contracts/AgentMech.sol
- contracts/AgentRegistry.sol
- contracts/ExtendedAgentFactory.sol
- contracts/MechMarketplace.sol
- contracts/integrations/nevermined/AgentFactorySubscription.sol
- contracts/integrations/nevermined/AgentMechSubscription.sol
- hardhat.config.js
> refactor: mech marketplace code refactor

- contracts/AgentFactory.sol
- contracts/AgentMech.sol
- contracts/ExtendedAgentFactory.sol
- contracts/Karma.sol
- contracts/KarmaProxy.sol
- contracts/MechMarketplace.sol
- contracts/integrations/nevermined/AgentFactorySubscription.sol
- contracts/integrations/nevermined/AgentMechSubscription.sol
- package.json
- test/AgentFactory.js
- test/AgentMech.js
- test/ExtendedAgentFactory.js
- yarn.lock
- Karma contract extracted to a separate one.
> refactor: karma contract extracted to a separate one

- README.md
- audit/internal1/README.md
- contracts/AgentMech.sol
- contracts/MechMarketplace.sol
- Re-audit marketplace based on stacking
- Re-write diagram (there are only key functions)
> doc: re-audit v0.3.1

- contracts/BalanceTrackerFixedPriceBase.sol
- contracts/BalanceTrackerFixedPriceNative.sol
- contracts/BalanceTrackerFixedPriceToken.sol
- contracts/MechMarketplace.sol
- contracts/integrations/nevermined/BalanceTrackerNvmSubscription.sol
- contracts/interfaces/IBalanceTracker.sol
- test/MechFixedPriceNative.js
- Fixing delivery recording bug;
- Adding more tests.
> fix: delivery recording bug

- contracts/test/ImportsSetup.sol
- test/MechFixedPriceNative.js
- test/MechFixedPriceToken.js
> test: adding more tests

- audit/internal5/README.md
- contracts/BalanceTrackerBase.sol
- contracts/MechMarketplace.sol
- contracts/OlasMech.sol
- contracts/interfaces/IErrorsMarketplace.sol
- contracts/mechs/nevermined/BalanceTrackerNvmSubscriptionNative.sol
> refactor and chore: addressing audit comments

- contracts/BalanceTrackerBase.sol
- contracts/MechMarketplace.sol
- contracts/OlasMech.sol
- contracts/interfaces/IBalanceTracker.sol
- contracts/interfaces/IErrorsMarketplace.sol
- contracts/interfaces/IMech.sol
- contracts/interfaces/IMechMarketplace.sol
- Off-chain requests handling.
> refactor: initial off-chain requests handling

- contracts/BalanceTrackerBase.sol
- contracts/MechMarketplace.sol
- contracts/OlasMech.sol
- contracts/interfaces/IBalanceTracker.sol
- contracts/interfaces/IErrorsMarketplace.sol
- contracts/interfaces/IMech.sol
- contracts/interfaces/IMechMarketplace.sol
- contracts/mechs/native/BalanceTrackerFixedPriceNative.sol
- contracts/mechs/nevermined/BalanceTrackerNvmSubscription.sol
- contracts/mechs/token/BalanceTrackerFixedPriceToken.sol
- Refinement of balance trackers to comply with nvm subscription.
> refactor: balance trackers to comply with nvm subscription

- contracts/MechFixedPriceBase.sol
- contracts/MechMarketplace.sol
- contracts/OlasMech.sol
- contracts/interfaces/IErrorsMarketplace.sol
- contracts/interfaces/IErrorsMech.sol
- contracts/interfaces/IMech.sol
- contracts/mechs/nevermined/MechNvmSubscription.sol
- contracts/test/MockMech.sol
- test/MechFixedPriceNative.js
- test/MechMarketplace.js
- `requestId` uint256 to bytes32, adding signature testing.
> chore and test: requestId uint to bytes32, adding signature testing

- contracts/BalanceTrackerBase.sol
> fix: Issue 11

- contracts/MechMarketplace.sol
- Addressing issue 19;
- TESTS ARE FIXED IN THE NEXT PR.
> fix: addressing issue 19

- contracts/MechMarketplace.sol
- contracts/test/MockMech.sol
- test/MechFixedPriceNative.js
- test/MechFixedPriceToken.js
- test/MechMarketplace.js
- test/MechNvmSubscriptionNative.js
- Addressing issues 13, 26, 21 and partially 5 (except for the suggested deadline).
> fix: issues 13, 26, 21, and partially 5

- contracts/BalanceTrackerBase.sol
- contracts/MechMarketplace.sol
- contracts/interfaces/IErrorsMarketplace.sol
- test/MechFixedPriceNative.js
- test/MechFixedPriceToken.js
- Addressing issues 2, 22, 25, 39, 41, 42.
> fix: issues 2, 22, 25, 39, 41, 42

- contracts/MechFixedPriceBase.sol
- contracts/OlasMech.sol
- contracts/mechs/nevermined/MechNvmSubscriptionNative.sol
> fix: addressing issue 24

- contracts/BalanceTrackerBase.sol
- contracts/MechFactoryBase.sol
- contracts/MechFixedPriceBase.sol
- contracts/MechMarketplace.sol
- contracts/OlasMech.sol
- contracts/interfaces/IBalanceTracker.sol
- contracts/interfaces/IErrorsMarketplace.sol
- contracts/interfaces/IMech.sol
- contracts/interfaces/IMechMarketplace.sol
- contracts/mechs/native/MechFactoryFixedPriceNative.sol
- contracts/mechs/nevermined/MechFactoryNvmSubscriptionNative.sol
- contracts/mechs/nevermined/MechNvmSubscriptionNative.sol
- contracts/mechs/token/MechFactoryFixedPriceToken.sol
- contracts/test/MockMech.sol
- test/MechFixedPriceNative.js
- test/MechMarketplace.js
- test/MechNvmSubscriptionNative.js
- Addressing issues 15 and 23.
> refactor and fix: addressing issues 15 and 23

- contracts/MechMarketplace.sol
- contracts/mechs/token/BalanceTrackerFixedPriceToken.sol
> fix: addressing issue 33 and 10

- .gitignore
- contracts/MechMarketplace.sol
- foundry.toml
- scripts/deployment/deploy_03_mech_marketplace.sh
- Events modification in Mech Marketplace.
- Batch request is going to have array of request data-s emitted.
- Batch delivery with signatures is going to have request data along with delivery data. Note that it's only possible to read single events for each delivery.
- Batch onchain delivery: nothing is possible to change without a subsequent modification of Mech contract.
- Addressing issue #121.
> refactor: events modification in MM
